### ISSUE TITLE
Fix menu to work on github actions

### ISSUE THREAD

**Issue by RebekkaEB** [SEMteam4groupproject/team4groupproject#63]

**Comment by RebekkaEB** [comment]
could do this by making two environments, interactive and non-interactive, and having interactive call the menu and non-interactive output the sample reports. then setting the environment when running on github as non-interactive

**Comment by KirstenMc88** [comment]
I have tried adding a step into the workflow that simulates a user input of 0 so the app would exit the menu automatically? seemed easier than creating a whole environment for it? but it didnt work

**Comment by KirstenMc88** [comment]
tried adding the echo to the build step instead, didnt work

**Comment by KirstenMc88** [comment]
added code to set environment for non interactive mode, this should mean that workflow is not waiting (and failing) on user input when none can be found. the app still works when running locally or by running the groupproject.jar in target directory after compiling with maven
